### ISSUE TITLE
Missing HOI_ISG Folder

### ISSUE THREAD

**Issue by Eladhi** [Kien085/SG2Caps#1]
Hi,

Thanks for sharing the project.

I'm trying to run vis/test.py. The README mention both HOI_ISG and all_ISG for that purpose.
But, only all_ISG is actually required and appear in the google drive folder.

Does all_ISG contain the information from the HOI? If not, could you add it to the folder?

Thanks!

**Comment by Kien085** [comment]
all_ISG does contain all of the information from the HOI. I must have forgotten to upload the HOI_ISG folder; it's in the google drive now.
